'use strict';
const { test, expect } = require('@playwright/test');
const { gotoHome } = require('./helpers');
const ADMIN = `http://localhost:${process.env.E2E_ADMIN_PORT || 4312}`;

test('contact to admin to reviewed knowledge, without a customer email or model provider', async ({ page, context, request }) => {
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await gotoHome(page, { suppressOnboarding: true });
  await page.goto('/?lang=fr');
  await page.evaluate(() => window.Nota.contact.open());
  await expect(page.locator('#chat-panel')).toBeVisible();
  await expect(page.locator('#contact-dialog')).not.toBeVisible();
  const question = 'Où puis-je changer la langue de l’interface ?';
  await page.locator('#chat-text').fill(question);
  const sent = page.waitForResponse(r => r.url().endsWith('/support/messages') && r.request().method() === 'POST');
  await page.locator('#chat-send').click();
  const first = await (await sent).json();
  await expect(page.locator('#chat-courriel-row')).toBeHidden();
  const admin = await context.newPage();
  admin.on('pageerror', e => errors.push(e.message));
  const login = await request.post(ADMIN + '/api/admin/auth/request', { data: { email: 'admin@nota.local' } });
  await admin.goto(ADMIN + '/?lang=fr' + new URL((await login.json()).devLink).hash);
  await expect(admin.locator('.admin-rail')).toBeVisible();
  await admin.evaluate(id => { location.hash = '#/support?thread=' + id; }, first.threadId);
  await expect(admin.locator('#support-log')).toContainText(question);
  const answer = 'Utilisez le sélecteur de langue dans l’en-tête du site.';
  await admin.locator('#support-text').fill(answer);
  await admin.locator('#support-send').click();
  await expect(page.locator('#chat-log')).toContainText(answer, { timeout: 10000 });
  await admin.locator('.support-learn').click();
  await admin.locator('#knowledge-en-question').fill('Where can I change the interface language?');
  await admin.locator('#knowledge-en-answer').fill('Use the language selector in the site header.');
  await admin.locator('#knowledge-approved').check();
  await admin.locator('#support-knowledge-form button[type="submit"]').click();
  await expect(admin.locator('#support-knowledge-form')).toBeHidden();
  const otherContext = await page.context().browser().newContext();
  await otherContext.addInitScript(() => { localStorage.setItem('nota.introSeen', '1'); localStorage.setItem('nota.onboarded.v1', '1'); });
  const visitor = await otherContext.newPage();
  visitor.on('pageerror', e => errors.push(e.message));
  try {
    await visitor.goto(page.url().split('#')[0]);
    await visitor.evaluate(() => window.Nota.contact.open());
    await visitor.locator('#chat-text').fill(question);
    await visitor.locator('#chat-send').click();
    await expect(visitor.locator('#chat-log .sup-msg[data-de="assistant"]')).toContainText(answer);
    await page.setViewportSize({ width: 390, height: 700 });
    await page.locator('#chat-text').fill('Merci');
    const panel = await page.locator('#chat-panel').boundingBox();
    expect(panel.x).toBeGreaterThanOrEqual(0);
    expect(panel.x + panel.width).toBeLessThanOrEqual(391);
    await page.screenshot({ path: '/tmp/nota-live-support-mobile.png' });
    await admin.screenshot({ path: '/tmp/nota-live-support-admin.png', fullPage: true });
    await admin.locator('.support-knowledge-entry summary').first().click();
    await admin.locator('.support-knowledge-entry button').filter({ hasText: 'Retirer cette réponse' }).first().click();
    await expect(admin.locator('#support-knowledge-status')).toContainText('Réponse retirée');
    expect(errors).toEqual([]);
  } finally { await otherContext.close(); }
});
